# the FQDN that your registry should be reachable at locally
# cache_registry_fqdn: registry.domain.com
# the FQDN that your traefik dashboard will be available at
# cache_traefik_fqdn: traefik.domain.com
# Requisite packages for docker cache
# cache_packages:
#   - docker-compose
# Dockerhub user name
# cache_docker_login_user: my_dockerhub_username
# Dockerhub login access token generated at https://hub.docker.com/settings/security
# cache_docker_access_token: my_dockerhub_token
# Host path to mount into docker cache
# cache_docker_host_path: /mnt/registry
# Email to associate with Lets Encrypt cert
# cache_le_tls_email: le_tls_cert_email
# Lets Encrypt ACME api to use; either 'prod' or 'staging'
# cache_le_acme_environment: staging
# AWS access key for use with Lets Encrypt DNS01 challenge (Route 53)
# cache_aws_access_key_id: my_aws_access_key_id
# cache_aws_secret_access_key: my_aws_secret_access_key
# AWS Region in which your Route 53 records exist
# cache_aws_region: us-east-1
# AWS nameservers to verify domain ownership
# cache_aws_resolver_ips:
#  - "205.251.194.46"
#  - "205.251.197.222"